http {
    root ./www;
    client_max_body_size 20M;
#index  dddkdkk
    server {
          listen 127.0.0.1:8080;
        error_page 404 /errors/404.html;
        error_page 502 /errors/502.html;

        location /old-page {
            return 301 /new-page.html;
                }

        location /new-page.html {
            index index.html test.py;
        }

        location /images {
            autoindex on;
            error_page 404 /errors/404.html;
            error_page 502 /errors/502.html;

        }

        location /uploads {
            allowed_methods POST;
            root ./www;
        }

        location /cgi {
            cgi .py /usr/bin/python3;
            cgi .php /usr/bin/php;
        }
    }

}