http {
    root ./webroot;
    #index index.html;
    client_max_body_size 10M;
    error_page 403 /errors/403.html;
    error_page 404 /errors/404.html;
    error_page 500 /errors/500.html;

    server {
        listen 127.0.0.1:8080;

        location / {
			index index.txt index.html;
            allowed_methods GET HEAD;
        }

        location /blog {
            allowed_methods GET HEAD;
            index post1.html;
        }

        location /images {
            allowed_methods GET HEAD;
            autoindex on;
        }

        location /forms {
            allowed_methods GET HEAD POST;
            index contact_form.html;
        }

        location /uploads {
            allowed_methods GET HEAD POST DELETE;
            client_max_body_size 1G;
            autoindex on;
        }

        location /cgi-bin {
            allowed_methods GET HEAD POST;
            cgi .py /usr/bin/python3;
            cgi .php /usr/bin/php;
        }
    }

    server {
        listen 127.0.0.1:7070;

        location / {
            allowed_methods GET HEAD;
            index index.html;
        }

        location /assets {
            allowed_methods GET HEAD;
            autoindex on;
        }

        location /old-url {
            allowed_methods GET HEAD;
            return 301 /blog/post2.html;
        }
    }
}
